version: '3.4'

services:
  timetracking.reportgenerator.webapi:
    image: dockersupportbankweb/timetrackreportsapi:latest
    build:
      context: .
      dockerfile: src/ReportGenerator/TimeTracking.ReportGenerator.WebApi/Dockerfile

  timetracking.webapi:
    image: dockersupportbankweb/timetrackwebapi:latest
    build:
      context: .
      dockerfile: src/TimeTracking/TimeTracking.WebApi/Dockerfile


  timetracking.identity.webapi:
    image: dockersupportbankweb/timetrackidentiy:latest
    build:
      context: .
      dockerfile: src/Identity/TimeTracking.Identity.WebApi/Dockerfile
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    
  healthcheck:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: src/CrossCutting/HealthMonitoring/Dockerfile
      
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500"
volumes:
    elasticsearch-data:
 
