version: '3.4'

services:
  timetracking.reportgenerator.webapi:
    image: ${DOCKER_REGISTRY-}timetrackingreportgeneratorwebapi
    build:
      context: .
      dockerfile: src/ReportGenerator/TimeTracking.ReportGenerator.WebApi/Dockerfile

  timetracking.webapi:
    image: ${DOCKER_REGISTRY-}timetrackingwebapi
    build:
      context: .
      dockerfile: src/TimeTracking/TimeTracking.WebApi/Dockerfile


  timetracking.identity.webapi:
    image: ${DOCKER_REGISTRY-}timetrackingidentitywebapi
    build:
      context: .
      dockerfile: src/Identity/TimeTracking.Identity.WebApi/Dockerfile

